### ISSUE TITLE
hey fristhon i am a big fan of your telminal wanted to ask something

### ISSUE THREAD

**Issue by nishchalrajput22** [fristhon/fristhon#1]
when i keep telminal idle it starts saying command not found for everything i type
i dont know much about coding learning please help 
i am using VPS with fedora
thanks for this awesome project…

**Comment by fristhon** [comment]
Hey. glad you liked the project
Don't worry there is no need for coding because you don't have to change the code. just basic knowledge about Linux commands is enough.
Please recheck videos and README and try to install it again. if it's possible for you test it in another environment, something like google colab can be good.
To be honest your problem is so weird and I can't understand why something like that can happen in the code, but please make another issue in the project repo with more details to discuss :
https://github.com/fristhon/telminal

Edit:
Created one step by step notebook to follow:
https://colab.research.google.com/drive/1mnMmXHEs8Um4AaH4dToswcRHNOEi50_f?usp=sharing

**Comment by nishchalrajput22** [comment]
wow you are so cool thanks
